from app import db
from app.models import BloodBank


BLOOD_BANK_SEED_DATA = [
    {
        'province': 'Koshi Pradesh',
        'district': 'Jhapa',
        'name': 'Mechi Blood Transfusion Service',
        'display_name': 'Mechi Blood Transfusion Service',
        'branch_type': 'Main Branch',
        'latitude': 26.5492,
        'longitude': 88.0910,
        'contact_number': '023-452087',
        'is_emergency_panel': False,
        'is_grouped_entry': False,
        'status': 'active',
        'notes': 'Main branch',
    },
    {
        'province': 'Bagmati Pradesh',
        'district': 'Kathmandu',
        'name': 'Central Blood Transfusion Service',
        'display_name': 'Central Blood Transfusion Service',
        'branch_type': 'Main Branch',
        'latitude': 27.7018,
        'longitude': 85.3184,
        'contact_number': '01-5322741',
        'is_emergency_panel': True,
        'is_grouped_entry': False,
        'status': 'active',
        'notes': 'National center',
    },
    {
        'province': 'Gandaki Pradesh',
        'district': 'Kaski',
        'name': 'Regional Blood Transfusion Service, Pokhara',
        'display_name': 'Regional Blood Transfusion Service',
        'branch_type': 'Regional Center',
        'latitude': 28.2120,
        'longitude': 83.9912,
        'contact_number': '061-521091',
        'is_emergency_panel': False,
        'is_grouped_entry': False,
        'status': 'active',
        'notes': 'Pokhara branch',
    },
    {
        'province': 'Lumbini Pradesh',
        'district': 'Rupandehi',
        'name': 'Butwal Blood Transfusion Centre',
        'display_name': 'Butwal Blood Transfusion Centre',
        'branch_type': 'Regional Center',
        'latitude': 27.7006,
        'longitude': 83.4661,
        'contact_number': '071-550462',
        'is_emergency_panel': False,
        'is_grouped_entry': False,
        'status': 'active',
        'notes': 'Western Terai branch',
    },
    {
        'province': 'Karnali Pradesh',
        'district': 'Jumla',
        'name': 'KAHS Blood Bank',
        'display_name': 'KAHS Blood Bank',
        'branch_type': 'Hospital Branch',
        'latitude': 29.2748,
        'longitude': 82.1837,
        'contact_number': '087-520115',
        'is_emergency_panel': False,
        'is_grouped_entry': False,
        'status': 'active',
        'notes': 'Karnali health science branch',
    },
    {
        'province': 'Sudurpashchim Pradesh',
        'district': 'Kailali',
        'name': 'Kailali District Blood Center',
        'display_name': 'Kailali District Blood Center',
        'branch_type': 'District Center',
        'latitude': 28.6847,
        'longitude': 80.5921,
        'contact_number': '091-521333',
        'is_emergency_panel': False,
        'is_grouped_entry': False,
        'status': 'active',
        'notes': 'Far-west branch',
    },
    {
        'province': 'Bagmati Pradesh',
        'district': 'Lalitpur',
        'name': 'Lalitpur Red Cross Blood Bank',
        'display_name': 'Lalitpur Red Cross Blood Bank',
        'branch_type': 'Branch',
        'latitude': 27.6775,
        'longitude': 85.3167,
        'contact_number': '01-5427033',
        'is_emergency_panel': False,
        'is_grouped_entry': False,
        'status': 'active',
        'notes': 'Pulchowk branch',
    },
    {
        'province': 'Madhesh Pradesh',
        'district': 'Saptari',
        'name': 'Gajendra Narayan Singh Hospital Blood Unit',
        'display_name': 'Gajendra Narayan Singh Hospital Blood Unit',
        'branch_type': 'Hospital Branch',
        'latitude': 26.5412,
        'longitude': 86.7521,
        'contact_number': '031-521087',
        'is_emergency_panel': False,
        'is_grouped_entry': True,
        'status': 'active',
        'notes': 'Grouped entry preserved',
    },
    {
        'province': 'Gandaki Pradesh',
        'district': 'Mustang',
        'name': 'District Hospital Jomsom',
        'display_name': 'District Hospital Jomsom',
        'branch_type': 'Emergency Panel',
        'latitude': 28.7845,
        'longitude': 83.7215,
        'contact_number': '069-440055',
        'is_emergency_panel': True,
        'is_grouped_entry': False,
        'status': 'active',
        'notes': 'Emergency panel',
    },
    {
        'province': 'Karnali Pradesh',
        'district': 'Dolpa',
        'name': 'District Hospital Dunai',
        'display_name': 'District Hospital Dunai',
        'branch_type': 'Emergency Panel',
        'latitude': 29.0014,
        'longitude': 82.6812,
        'contact_number': '087-550155',
        'is_emergency_panel': True,
        'is_grouped_entry': False,
        'status': 'active',
        'notes': 'Emergency panel',
    },
]


def seed_blood_banks():
    inserted = 0
    for payload in BLOOD_BANK_SEED_DATA:
        existing = BloodBank.query.filter_by(name=payload['name']).first()
        if existing:
            continue
        maps_url = payload.get('maps_url')
        if not maps_url and payload.get('latitude') is not None and payload.get('longitude') is not None:
            maps_url = f"https://www.google.com/maps?q={payload['latitude']},{payload['longitude']}"

        bank = BloodBank(
            name=payload['name'],
            display_name=payload.get('display_name', payload['name']),
            province=payload['province'],
            district=payload['district'],
            latitude=payload.get('latitude'),
            longitude=payload.get('longitude'),
            contact_number=payload.get('contact_number'),
            phone=payload.get('contact_number'),
            google_maps=payload.get('google_maps_url') or None,
            maps_url=maps_url,
            is_emergency_panel=payload.get('is_emergency_panel', False),
            is_grouped_entry=payload.get('is_grouped_entry', False),
            notes=payload.get('notes'),
            status=payload.get('status', 'active'),
            is_active=True,
            service_type=payload.get('branch_type', 'Hospital Blood Bank'),
            hospital_name=payload.get('display_name', payload['name']),
        )
        db.session.add(bank)
        inserted += 1
    db.session.commit()
    return inserted
