"""Production Grade Upgrade

Revision ID: 0863441bfaf3
Revises: 
Create Date: 2026-06-21 09:03:04.793752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0863441bfaf3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blood_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('province', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('district', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('local_level', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ward_no', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fulfilled_date', sa.DateTime(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_blood_requests_district'), ['district'], unique=False)
        batch_op.create_foreign_key('fk_blood_requests_creator_id', 'donors', ['creator_id'], ['id'])
        batch_op.drop_column('hospital_address')

    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('pin_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('perm_ward', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('perm_tole', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('curr_ward', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('curr_tole', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('available_after', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('is_email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_phone_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.alter_column('curr_local_level',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('availability_status',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_donors_curr_city'))
        batch_op.drop_index(batch_op.f('ix_donors_phone1'))
        batch_op.create_index(batch_op.f('ix_donors_phone1'), ['phone1'], unique=True)
        batch_op.drop_column('perm_city')
        batch_op.drop_column('curr_city')

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('success_stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('district', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('blood_group', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('video_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('social_link', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('moderation_logs', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('image_file',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_success_stories_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('success_stories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_success_stories_status'))
        batch_op.alter_column('image_file',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('moderation_logs')
        batch_op.drop_column('status')
        batch_op.drop_column('social_link')
        batch_op.drop_column('video_url')
        batch_op.drop_column('blood_group')
        batch_op.drop_column('district')

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('scheduled_date')

    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('curr_city', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('perm_city', sa.VARCHAR(length=100), nullable=True))
        pass
        batch_op.drop_index(batch_op.f('ix_donors_phone1'))
        batch_op.create_index(batch_op.f('ix_donors_phone1'), ['phone1'], unique=False)
        batch_op.create_index(batch_op.f('ix_donors_curr_city'), ['curr_city'], unique=False)
        batch_op.alter_column('availability_status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
        batch_op.alter_column('curr_local_level',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('is_active')
        batch_op.drop_column('is_phone_verified')
        batch_op.drop_column('is_email_verified')
        batch_op.drop_column('available_after')
        batch_op.drop_column('curr_tole')
        batch_op.drop_column('curr_ward')
        batch_op.drop_column('perm_tole')
        batch_op.drop_column('perm_ward')
        batch_op.drop_column('pin_hash')
        batch_op.drop_column('email')

    with op.batch_alter_table('blood_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hospital_address', sa.VARCHAR(length=300), nullable=True))
        batch_op.drop_constraint('fk_blood_requests_creator_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_blood_requests_district'))
        batch_op.alter_column('status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
        batch_op.drop_column('fulfilled_date')
        batch_op.drop_column('creator_id')
        batch_op.drop_column('ward_no')
        batch_op.drop_column('local_level')
        batch_op.drop_column('district')
        batch_op.drop_column('province')

    # ### end Alembic commands ###
