"""add bag models

Revision ID: 29b7efbe9077
Revises: 79e548adfbf6
Create Date: 2026-07-12 21:54:20.810306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29b7efbe9077'
down_revision = '79e548adfbf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_audit_logs')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.drop_column('user_id')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('module')

    with op.batch_alter_table('blood_banks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blood_banks_is_emergency_panel'), ['is_emergency_panel'], unique=False)
        batch_op.create_index(batch_op.f('ix_blood_banks_is_grouped_entry'), ['is_grouped_entry'], unique=False)

    with op.batch_alter_table('blood_inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blood_inventory_qr_code'), ['qr_code'], unique=True)

    with op.batch_alter_table('blood_requests', schema=None) as batch_op:
        batch_op.alter_column('request_message',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('blood_reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blood_reservations_qr_code'), ['qr_code'], unique=True)

    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('pin_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('donor_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.create_index('idx_donor_search', ['curr_district', 'blood_group', 'availability_status'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_blood_request_id'), ['blood_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_donor_id'), ['donor_id'], unique=False)
        batch_op.create_foreign_key('fk_notifications_blood_request_id', 'blood_requests', ['blood_request_id'], ['id'])
        batch_op.create_foreign_key('fk_notifications_donor_id', 'donors', ['donor_id'], ['id'])

    with op.batch_alter_table('success_stories', schema=None) as batch_op:
        batch_op.alter_column('social_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('success_stories', schema=None) as batch_op:
        batch_op.alter_column('social_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_notifications_donor_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_blood_request_id'))

    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.drop_index('idx_donor_search')
        batch_op.alter_column('donor_type',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('pin_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('blood_reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blood_reservations_qr_code'))

    with op.batch_alter_table('blood_requests', schema=None) as batch_op:
        batch_op.alter_column('request_message',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('blood_inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blood_inventory_qr_code'))

    with op.batch_alter_table('blood_banks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blood_banks_is_grouped_entry'))
        batch_op.drop_index(batch_op.f('ix_blood_banks_is_emergency_panel'))

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)
        batch_op.alter_column('action',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    op.create_table('_alembic_tmp_audit_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('action', sa.VARCHAR(length=80), nullable=False),
    sa.Column('details', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('entity_id', sa.INTEGER(), nullable=True),
    sa.Column('actor', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
