"""Split Tenant tables and add tenant fields to BloodBank

Revision ID: f99e3749c73f
Revises: 29b7efbe9077
Create Date: 2026-07-12 22:31:23.181073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f99e3749c73f'
down_revision = '29b7efbe9077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # We DO NOT drop the legacy tenant tables here to prevent data loss.
    # Data will be migrated to the individual tenant databases via a separate script later.
    with op.batch_alter_table('blood_banks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blood_banks_tenant_id'), ['tenant_id'], unique=True)
        batch_op.create_unique_constraint('uq_blood_banks_db_name', ['db_name'])

    # We intentionally skip dropping unnamed foreign key constraints
    # because SQLite batch mode requires names and these tables
    # are already in the Main DB where the constraints are valid anyway.

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_notifications_blood_request_id'), 'blood_requests', ['blood_request_id'], ['id'])

    with op.batch_alter_table('donor_responses', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'blood_requests', ['blood_request_id'], ['request_id'])

    with op.batch_alter_table('blood_requests', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_blood_requests_creator_id'), 'donors', ['creator_id'], ['id'])

    with op.batch_alter_table('blood_banks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_blood_banks_tenant_id'))

    op.create_table('staff_members',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('designation', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('contact_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('profile_photo', sa.VARCHAR(length=255), nullable=True),
    sa.Column('province', sa.VARCHAR(length=60), nullable=True),
    sa.Column('district', sa.VARCHAR(length=80), nullable=True),
    sa.Column('local_level', sa.VARCHAR(length=100), nullable=True),
    sa.Column('ward_number', sa.VARCHAR(length=10), nullable=True),
    sa.Column('tole', sa.VARCHAR(length=100), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blood_bags',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('bag_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('blood_bank_id', sa.INTEGER(), nullable=False),
    sa.Column('donor_id', sa.INTEGER(), nullable=True),
    sa.Column('blood_group', sa.VARCHAR(length=5), nullable=False),
    sa.Column('component', sa.VARCHAR(length=50), nullable=False),
    sa.Column('volume_ml', sa.INTEGER(), nullable=True),
    sa.Column('collection_date', sa.DATETIME(), nullable=True),
    sa.Column('expiry_date', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('qr_code', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['blood_bank_id'], ['blood_banks.id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blood_bags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blood_bags_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_blood_bags_qr_code'), ['qr_code'], unique=1)
        batch_op.create_index(batch_op.f('ix_blood_bags_expiry_date'), ['expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_blood_bags_donor_id'), ['donor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blood_bags_blood_group'), ['blood_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_blood_bags_blood_bank_id'), ['blood_bank_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blood_bags_bag_id'), ['bag_id'], unique=1)

    op.create_table('blood_inventory_movements',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('inventory_id', sa.INTEGER(), nullable=False),
    sa.Column('movement_type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('units', sa.INTEGER(), nullable=True),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['blood_inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blood_inventory_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blood_inventory_movements_movement_type'), ['movement_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_blood_inventory_movements_inventory_id'), ['inventory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blood_inventory_movements_created_at'), ['created_at'], unique=False)

    op.create_table('low_stock_alerts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('blood_bank_id', sa.INTEGER(), nullable=False),
    sa.Column('blood_group', sa.VARCHAR(length=5), nullable=False),
    sa.Column('component', sa.VARCHAR(length=50), nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), nullable=True),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['blood_bank_id'], ['blood_banks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('low_stock_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_low_stock_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_low_stock_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_low_stock_alerts_blood_group'), ['blood_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_low_stock_alerts_blood_bank_id'), ['blood_bank_id'], unique=False)

    op.create_table('blood_transfers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('source_bank_id', sa.INTEGER(), nullable=False),
    sa.Column('destination_bank_id', sa.INTEGER(), nullable=False),
    sa.Column('blood_group', sa.VARCHAR(length=5), nullable=False),
    sa.Column('component', sa.VARCHAR(length=50), nullable=False),
    sa.Column('units', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('remarks', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['destination_bank_id'], ['blood_banks.id'], ),
    sa.ForeignKeyConstraint(['source_bank_id'], ['blood_banks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blood_transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blood_transfers_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_blood_transfers_source_bank_id'), ['source_bank_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blood_transfers_destination_bank_id'), ['destination_bank_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blood_transfers_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_blood_transfers_blood_group'), ['blood_group'], unique=False)

    op.create_table('lab_test_results',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('bag_id', sa.INTEGER(), nullable=False),
    sa.Column('test_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('result', sa.VARCHAR(length=20), nullable=True),
    sa.Column('tested_at', sa.DATETIME(), nullable=True),
    sa.Column('tested_by', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['bag_id'], ['blood_bags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lab_test_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lab_test_results_bag_id'), ['bag_id'], unique=False)

    op.create_table('blood_inventory',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('blood_bank_id', sa.INTEGER(), nullable=False),
    sa.Column('blood_group', sa.VARCHAR(length=5), nullable=False),
    sa.Column('component', sa.VARCHAR(length=50), nullable=False),
    sa.Column('units_available', sa.INTEGER(), nullable=True),
    sa.Column('units_reserved', sa.INTEGER(), nullable=True),
    sa.Column('minimum_stock', sa.INTEGER(), nullable=True),
    sa.Column('maximum_stock', sa.INTEGER(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.Column('expiry_date', sa.VARCHAR(length=20), nullable=True),
    sa.Column('qr_code', sa.VARCHAR(length=80), nullable=True),
    sa.ForeignKeyConstraint(['blood_bank_id'], ['blood_banks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blood_inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blood_inventory_qr_code'), ['qr_code'], unique=1)
        batch_op.create_index(batch_op.f('ix_blood_inventory_blood_group'), ['blood_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_blood_inventory_blood_bank_id'), ['blood_bank_id'], unique=False)

    op.create_table('blood_inventory_transactions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('bag_id', sa.INTEGER(), nullable=True),
    sa.Column('blood_bank_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['bag_id'], ['blood_bags.id'], ),
    sa.ForeignKeyConstraint(['blood_bank_id'], ['blood_banks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blood_inventory_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blood_inventory_transactions_transaction_type'), ['transaction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_blood_inventory_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_blood_inventory_transactions_blood_bank_id'), ['blood_bank_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blood_inventory_transactions_bag_id'), ['bag_id'], unique=False)

    op.create_table('blood_reservations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('blood_bank_id', sa.INTEGER(), nullable=False),
    sa.Column('hospital_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('patient_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('blood_group', sa.VARCHAR(length=5), nullable=False),
    sa.Column('component', sa.VARCHAR(length=50), nullable=False),
    sa.Column('units', sa.INTEGER(), nullable=True),
    sa.Column('priority', sa.VARCHAR(length=20), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('requested_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('qr_code', sa.VARCHAR(length=80), nullable=True),
    sa.ForeignKeyConstraint(['blood_bank_id'], ['blood_banks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blood_reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blood_reservations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_blood_reservations_requested_at'), ['requested_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_blood_reservations_qr_code'), ['qr_code'], unique=1)
        batch_op.create_index(batch_op.f('ix_blood_reservations_blood_group'), ['blood_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_blood_reservations_blood_bank_id'), ['blood_bank_id'], unique=False)

    # ### end Alembic commands ###
